apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-b
  labels:
    app: programmableweb
    purpose: demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: programmableweb
      purpose: demo
  template:
    metadata:
      labels:
        app: programmableweb
        purpose: demo
    spec:
      containers:
      - name: simple-server-b
        image: reselbob/simple-server-b:1.0
        ports:
        - containerPort: 3030