apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-a
  labels:
    app: programmableweb
    purpose: dev
spec:
  replicas: 3
  selector:
    matchLabels:
      app: programmableweb
      purpose: dev
  template:
    metadata:
      labels:
        app: programmableweb
        purpose: dev
    spec:
      containers:
      - name: simple-server-a
        image: reselbob/simple-server-a:1.0
        ports:
        - containerPort: 3030
