apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-two
  labels:
    app: programmableweb
    purpose: dev
spec:
  replicas: 3
  selector:
    matchLabels:
      app: programmableweb
      purpose: dev
  template:
    metadata:
      labels:
        app: programmableweb
        purpose: dev
    spec:
      containers:
      - name: simple-server-b
        image: reselbob/simple-server-b:1.0
        ports:
        - containerPort: 3030
