apiVersion: v1
kind: Service
metadata:
  name: myservice
spec:
  selector:
    app: programmableweb
    purpose: demo
  ports:
  -
    protocol: TCP
    port: 3030
    targetPort: 3030
  type: NodePort