apiVersion: v1
kind: Service
metadata:
  name: myservice
spec:
  selector:
    app: programmableweb
    purpose: demo
  ports:
  -
    protocol: TCP
    port: 3000
    targetPort: 3000
  type: NodePort